{% set name = "pyproject-flake8" %}
{% set version = "7.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 5b953592336bc04d86e8942fdca1014256044a3445c8b6ca9467d08636749158

build:
  entry_points:
    - pflake8=pflake8.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - flit-core >=3.2,<4
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - tomli
    - flake8 =={{ version }}

test:
  imports:
    - pflake8
  commands:
    - pip check
    - pflake8 --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/csachs/pyproject-flake8
  summary: Monkey patching wrapper to connect flake8 with pyproject.toml configuration
  license: Unlicense
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
